### ISSUE TITLE
No module named ''facexlib'

### ISSUE THREAD

**Issue by KumaPlayWithShader** [ArtBot2023/CharacterFaceSwap#1]
is:issue is:open Cannot import F:\ComfyUI_Portable\ComfyUI\custom_nodes\CharacterFaceSwap module for custom nodes: 
No module named 'facexlib'

**Comment by ArtBot2023** [comment]
If you use comfyui manager, requirements should be installed automatically.
For manual install, you need to install requirements by `pip install -r requirements.txt`

**Comment by ArtBot2023** [comment]
facexlib now added as local package, you can reinstall CharacterFaceSwap
